//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactDetails.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        [Required(ErrorMessage ="This field is required")]
        [Display(Name ="Person Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name ="Contact Number")]
        public string ContactNo { get; set; }
        public int ID { get; set; }
    }
}
